import type { Metadata } from "next";
import { getAllPosts, getPostBySlug, getPostTranslations } from "@/lib/content";
import {
  loadZoeConfig,
  buildAlternatesForTranslations,
  getDefaultLocale,
  getSiteMetadata,
  isI18nEnabled,
} from "@/lib/zoefile";
import { getLabel } from "@/lib/i18n";
import { BlogPostView } from "@/components/views/blog-post-view";

/**
 * Resolve a usable OG image for this post.
 *
 * Why no dynamic `opengraph-image.tsx`: Next.js 16 static export double-encodes
 * non-ASCII slugs in the auto-injected OG URL (e.g. `把人生托管到-github` becomes
 * `%25E6%258A%258A...` instead of `%E6%8A%8A...`), 404'ing the dynamic route.
 * Until that's fixed upstream, we fall back to:
 *   1. post.banner (per-post hero image)
 *   2. site.image (sitewide default — e.g. /images/og.png)
 */
function resolveOgImage(banner: string | undefined, siteImage: string | undefined): string | undefined {
  return banner || siteImage || undefined;
}

interface PostPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  // Default-locale posts only. Non-default-locale posts are generated by
  // [lang]/blog/[slug]/page.tsx.
  try {
    const locale = isI18nEnabled() ? getDefaultLocale() : undefined;
    const posts = getAllPosts(false, locale);
    if (posts.length === 0) {
      // Placeholder keeps `output: export` happy when content sync hasn't run yet.
      return [{ slug: "__placeholder__" }];
    }
    return posts.map((post) => ({ slug: post.slug }));
  } catch (error) {
    console.warn("[blog/[slug]] Failed to generate static params:", error);
    return [{ slug: "__placeholder__" }];
  }
}

export async function generateMetadata({ params }: PostPageProps): Promise<Metadata> {
  const { slug } = await params;
  const locale = isI18nEnabled() ? getDefaultLocale() : undefined;
  const post = getPostBySlug(slug, locale);

  if (!post) {
    return { title: getLabel(loadZoeConfig(), "blog.postNotFound") };
  }

  // Build hreflang alternates from translations
  const translations = getPostTranslations(post);
  const slugByLocale = new Map<string, string>();
  for (const [loc, p] of translations) slugByLocale.set(loc, p.slug);
  const alternates = buildAlternatesForTranslations(
    slugByLocale,
    (s) => `/blog/${s}`,
    locale || getDefaultLocale(),
  );

  // Resolve OG image: post.banner wins; otherwise fall back to the sitewide image.
  const site = getSiteMetadata();
  const ogImage = post.banner
    ? post.banner
    : resolveOgImage(undefined, site.image);

  return {
    title: post.title,
    description: post.description || post.excerpt,
    alternates: Object.keys(alternates).length ? alternates : undefined,
    openGraph: {
      title: post.title,
      description: post.description || post.excerpt,
      type: "article",
      publishedTime: post.date ? new Date(post.date).toISOString() : undefined,
      modifiedTime: post.modifiedDate ? new Date(post.modifiedDate).toISOString() : undefined,
      ...(ogImage ? { images: [ogImage] } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description || post.excerpt,
      ...(ogImage ? { images: [ogImage] } : {}),
    },
  };
}

export default async function PostPage({ params }: PostPageProps) {
  const { slug } = await params;
  const locale = isI18nEnabled() ? getDefaultLocale() : undefined;
  return <BlogPostView slug={slug} locale={locale} />;
}
