import type { Metadata } from "next";
import { getAllPosts, getPostBySlug, getPostTranslations } from "@/lib/content";
import {
  loadZoeConfig,
  buildAlternatesForTranslations,
  getDefaultLocale,
  isI18nEnabled,
} from "@/lib/zoefile";
import { getLabel } from "@/lib/i18n";
import { BlogPostView } from "@/components/views/blog-post-view";

interface PostPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  // Default-locale posts only. Non-default-locale posts are generated by
  // [lang]/blog/[slug]/page.tsx.
  const locale = isI18nEnabled() ? getDefaultLocale() : undefined;
  const posts = getAllPosts(false, locale);
  return posts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: PostPageProps): Promise<Metadata> {
  const { slug } = await params;
  const locale = isI18nEnabled() ? getDefaultLocale() : undefined;
  const post = getPostBySlug(slug, locale);

  if (!post) {
    return { title: getLabel(loadZoeConfig(), "blog.postNotFound") };
  }

  // Build hreflang alternates from translations
  const translations = getPostTranslations(post);
  const slugByLocale = new Map<string, string>();
  for (const [loc, p] of translations) slugByLocale.set(loc, p.slug);
  const alternates = buildAlternatesForTranslations(
    slugByLocale,
    (s) => `/blog/${s}`,
  );

  return {
    title: post.title,
    description: post.description || post.excerpt,
    alternates: Object.keys(alternates).length ? alternates : undefined,
    openGraph: {
      title: post.title,
      description: post.description || post.excerpt,
      type: "article",
      publishedTime: post.date ? new Date(post.date).toISOString() : undefined,
      modifiedTime: post.modifiedDate ? new Date(post.modifiedDate).toISOString() : undefined,
      ...(post.banner ? { images: [post.banner] } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description || post.excerpt,
      ...(post.banner ? { images: [post.banner] } : {}),
    },
  };
}

export default async function PostPage({ params }: PostPageProps) {
  const { slug } = await params;
  const locale = isI18nEnabled() ? getDefaultLocale() : undefined;
  return <BlogPostView slug={slug} locale={locale} />;
}
